server:
  port: 3000
  log_level: "debug"
  writeTimeout: 10 # Sedonds
  readTimeout: 10 # Seconds
  maxHeaderBytes: 1 # MB

database:
  username: "postgres"
  dbname: "travels"
  host: "localhost"
  port: 5432
  sslmode: "disable"

sessions:
  httpOnly: true
  maxAge: 30 # days
  secure: false