server:
  port: 3000
  log_level: "debug"
  writeTimeout: 10 # Seconds
  readTimeout: 10 # Seconds
  maxHeaderBytes: 1 # MB

database:
  username: "authenticate(h.sessionStore),"
  dbname: "std_1407_frontend"
  host: "std-mysql"
  port: 3306
  sslmode: "disable"

sessions:
  httpOnly: true
  maxAge: 30 # days
  secure: false